// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpqvomfrhhrgdxfqnwem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcXZvbWZyaGhyZ2R4ZnFud2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODM5NDAsImV4cCI6MjA2MzE1OTk0MH0.vibLra_-ccudURx8VorGBTzX9D6U_nDtRkB04PGMBI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);